### ISSUE TITLE
Missing _elemsList for Domain -> Codomain functions

### ISSUE THREAD

**Issue by isaacmaffeis** [isaacmaffeis/asmetal2java#16]
---
name: 🐞 Bug
about: File a bug/issue
title: '[BUG]  Missing _elemsList for Domain -> Codomain functions'
labels: Bug, Needs Triage
assignees: ''

---

### Current Behavior:
For functions that have domain and codomain, the _elemsList array is not generated

Asmeta signature:
```
controlled available: Product -> QuantityDomain
```

![image](https://github.com/user-attachments/assets/21c32b0d-fee6-479a-974a-e842a8dc7404)

### Expected Behavior:
In the Signature class (`coffeeVendingMachineNCSig`) I need this arrays to be generated:
```
List<Product> Product_elemsList = new ArrayList<>();
```

### Steps To Reproduce:
Run the MainClass : `org.asmeta.asm2java.main.MainClass`
With the following params:
```
-input
"input\coffeeVendingMachineNC.asm"
```

### Environment:
- OS: Windows11
- Java: JDK-17
- IDE: IntelliJ IDEA 2024

**Comment by isaacmaffeis** [comment]
Also we need to add this to the class the sxtends the signature (`coffeeVendingMachineNC ` extends `coffeeVendingMachineNCSig`) :
```
  CoinType_elemsList = Collections.unmodifiableList(Arrays.asList(CoinType.HALF, CoinType.ONE));
  Product_elemsList = Collections.unmodifiableList(Arrays.asList(Product.COFFEE, Product.TEA, Product.MILK));
```
Otherwise we get this error when we run the class:
```
java.lang.ExceptionInInitializerError
	at org.evoservice.coffeeVendingMachineNC.coffeeVendingMachineNC_ASM_ESTest_scaffolding.initEvoSuiteFramework(coffeeVendingMachineNC_ASM_ESTest_scaffolding.java:30)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:232)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:55)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field private static java.lang.Boolean java.awt.GraphicsEnvironment.headless accessible: module java.desktop does not "opens java.awt" to unnamed module @1ed6993a
	at java.base/java.lang.reflect.AccessibleObject.throwInaccessibleObjectException(AccessibleObject.java:391)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:367)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:315)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:183)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:177)
	at org.evosuite.runtime.GuiSupport.<clinit>(GuiSupport.java:51)
	... 16 more
```

**Comment by isaacmaffeis** [comment]
Fixed this problem creating these _elemsList arrays for each enumerative domain, in this way the functions with codomain can access them immediately without problems

**Comment by isaacmaffeis** [comment]
Also added this :		
```
sb.append(System.lineSeparator)
		sb.append('''
			List<«object.name»> «object.name»_elemsList = new ArrayList<>();''')
```
to DomainToJavaSigDef.xtend at line 149
